### ISSUE TITLE
Header CSS Not Optimized

### ISSUE THREAD

**Issue by explodingmentos** [mrsilver512/xsnlwebdev#2]
The header CSS is not at an optimal reaction speed (on hover) as compared to the other buttons on the body.

**Comment by explodingmentos** [comment]
lol this issue tho haha

**Comment by mrsilver512** [comment]
haha ikr
wait why are we turning this into a chatroom haha

**Comment by mrsilver512** [comment]
but is that thing legit tho the header css or this is a test lol

**Comment by explodingmentos** [comment]
Ofc it's legit... haha

**Comment by mrsilver512** [comment]
no offense i dont get you since i removed the bug...probs the browser. May I ask what browser are you using?
